#ifndef __DataView__
#define __DataView__

/**
@file
Subclass of MyFrame1, which is generated by wxFormBuilder.
*/

#include "mainwindow.h"
#include "Calculation.hpp"

//// end generated include

/** Implementing MyFrame1 */
class DataView : public MyFrame1
{
	using MyFrame1::MyFrame1;

	Calculation calcdata;


	protected:
		// Handlers for MyFrame1 events.
		void ProductSelect( wxCommandEvent& event ) override;
		void U1rmsEnter( wxCommandEvent& event ) override;
		void R1Enter( wxCommandEvent& event ) override;
		void R2Enter( wxCommandEvent& event ) override;
		void U2Calc( wxCommandEvent& event ) override;
		void KyCalc( wxCommandEvent& event ) override;
		void RocCalc( wxCommandEvent& event ) override;
	
	//public:
		/** Constructor */
	// DataView( wxWindow* parent );
	//// end generated class members

};

#endif // __DataView__
