#ifndef __FormHandler__
#define __FormHandler__

/**
@file
Subclass of MyFrame1, which is generated by wxFormBuilder.
*/

#include "MainFrame.h"
#include "Calculation.hpp"
//// end generated include



/** Implementing MainFrame */
class FormHandler : public MainFrame
{
	using MainFrame::MainFrame;

	Calculation calcdata;


	protected:
		// Handlers for MainFrame events.
		void ProductSelect( wxCommandEvent& event ) override;
		void ADCVoltageSelect( wxCommandEvent& event ) override;
		void U1rmsEnter( wxCommandEvent& event ) override;
		void R1Enter( wxCommandEvent& event ) override;
		void R2Enter( wxCommandEvent& event ) override;
		void REnter( wxCommandEvent& event ) override;


	//public:
		/** Constructor */
	// FormHandler( wxWindow* parent );
	//// end generated class members

};

#endif // FormHandler
